# Site settings
name: Nick and Wendy
description: 'Casey gettin married'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://localhost:4000' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          false
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Nick Rau'
    email: ''
    uri: 'https://github.com/pettazz/nwrau'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate